import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import dataList from "../data/data";
import CustomButton from "../components/button";

const Home: NextPage = () => {
  const [isDark, setIsDark] = useState(false);
  const changeTheme = () => {
    setIsDark(() => !isDark);
  };

  const colorTheme = isDark ? " bg-black text-white" : " bg-white text-black";

  const [category, setCategory] = useState("flutter");
  const [data, setData] = useState(dataList.flutter);

  const changeProject = (chooseIndex: number): void => {
    const chooseItem = data[chooseIndex];
    //APPROACH 2
    const newList = data.filter((each) => each !== chooseItem);
    if (chooseIndex === 2) newList.reverse();
    newList.unshift(chooseItem);
    setData(newList);
  };

  const changeLang = (): void => {
    const list = ["flutter", "reactNative", "next"];
    let index = list.indexOf(category) + 1;
    if (index === list.length) index = 0;
    setCategory(list[index]);
    setData(dataList[category]);
  };

  useEffect(() => {
    setData(dataList[category]);
    console.log("useeffect ran");
  }, [category]);

  return (
    <div>
      <Head>
        <title>Apps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="grid grid-cols-3 h-screen">
          <div className="col-span-2">
            {/* title and intro */}
            <section className="h-2/3 border-black border-b">
              <div
                className="h-2/3 text-8xl uppercase flex items-center cursor-pointer"
                onClick={() => changeLang()}
              >
                {category}
              </div>
              <div className="border-black border-t flex items-center h-1/3">
                <p className="w-1/3 pl-4">
                  Hello, my name is Myo Thu Kha. And I love coding apps that
                  have beautiful UI. Here are the list of projects that I have
                  been created.
                </p>
              </div>
            </section>

            {/* others projects */}
            <section className="h-1/3 grid grid-cols-2">
              <div
                onClick={() => changeProject(1)}
                className="col-span-1 border-black border-r relative px-2"
              >
                <h2 className="uppercase text-2xl py-4">{data[1].title}</h2>
                <div>{data[1].about}</div>
                <CustomButton />
              </div>
              <div
                className="col-span-1 relative px-2"
                onClick={() => changeProject(2)}
              >
                <h2 className="uppercase text-2xl py-4">{data[2].title}</h2>
                <div>{data[2].about}</div>
                {/* button */}
                <CustomButton />
              </div>
            </section>
          </div>

          {/* Current Project */}
          <div className="col-span-1 p-4 border-black border-l">
            <h2 className="text-4xl uppercase">{data[0].title}</h2>
            <div className="p-2">{data[0].about}</div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
