import { AnimatePresence, motion } from "framer-motion";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import Content from "../components/content";

const Home: NextPage = () => {
  const [isDark, setIsDark] = useState(false);
  const changeTheme = () => {
    setIsDark(() => !isDark);
  };

  const colorTheme = isDark ? " bg-black text-white" : " bg-white text-black";
  return (
    <div>
      <Head>
        <title>Apps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="grid grid-cols-3 h-screen">
          <div className="col-span-2">
            {/* title and intro */}
            <section className="h-2/3 border-black border-b">
              <div className="h-2/3 text-8xl uppercase flex items-center">
                Flutter
              </div>
              <div className="border-black border-t flex">hello</div>
            </section>

            {/* others projects */}
            <section className="h-1/3 grid grid-cols-2">
              <div className="col-span-1 border-black border-r">categ1</div>
              <div className="col-span-1">categ2</div>
            </section>
          </div>

          {/* Current Project */}
          <div className="col-span-1 border-black border-l">
            <div></div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
